### ISSUE TITLE
help troubleshooting trying to figure out how to apply your hosted-basic-submod-vcpkg example yml to a wxWidgets example project 

### ISSUE THREAD

**Issue by ericfont** [lukka/CppBuildTasks-Validation#11]
I am trying to wrap my head around your hosted-basic-cache-submod system.  And so for practice I forked an example wxWidgets project (https://github.com/gammasoft71/Examples_wxWidgets) and copied your `hosted-basic-cache-submod_vcpkg.yml` and made appropriate modifications.  You can see the diff here: https://github.com/gammasoft71/Examples_wxWidgets/compare/master...ericfont:hosted-basic-submod-vcpkg (and instead of printing sqlite version as a test I have cmakeliststxt/print-version.cpp which prints the wxwidgets version).

However when I run the action, I get and error on the ubuntu-latest run:
https://github.com/ericfont/Examples_wxWidgets/runs/3775207527?check_suite_focus=true#step:6:452

```
  CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
      Command failed: /home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake /home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/buildtrees/wxwidgets/src/54f4f955a1-0d7c66a59e.clean -DwxUSE_REGEX=builtin -DwxUSE_ZLIB=sys -DwxUSE_EXPAT=sys -DwxUSE_LIBJPEG=sys -DwxUSE_LIBPNG=sys -DwxUSE_LIBTIFF=sys -DwxBUILD_DISABLE_PLATFORM_LIB_DIR=ON -DwxUSE_STL=OFF -DCMAKE_MAKE_PROGRAM=/home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/downloads/tools/ninja-1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg -D_VCPKG_INSTALLED_DIR=/home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/packages/wxwidgets_x64-linux/debug
      Working Directory: /home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/buildtrees/wxwidgets/x64-linux-dbg
      Error code: 1
      See logs for more information:
        /home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/buildtrees/wxwidgets/config-x64-linux-dbg-out.log
        /home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/buildtrees/wxwidgets/config-x64-linux-dbg-err.log
  
  Call Stack (most recent call first):
    scripts/cmake/vcpkg_configure_cmake.cmake:381 (vcpkg_execute_required_process)
    ports/wxwidgets/portfile.cmake:33 (vcpkg_configure_cmake)
    scripts/ports.cmake:141 (include)
  
  
  Error: Building package wxwidgets:x64-linux failed with: BUILD_FAILED
  Please ensure you're using the latest portfiles with `./vcpkg update`, then
  submit an issue at https://github.com/Microsoft/vcpkg/issues including:
    Package: wxwidgets:x64-linux
    Vcpkg version: 2021-09-10-unknownhash
  
  Additionally, attach any relevant sections from the log files above.
  Error: Last command execution failed with error code '1'.
⏱ elapsed: 65.846 seconds
Error: Last command execution failed with error code '1'.
    at BaseUtilLib.throwIfErrorCode (/home/runner/work/_actions/lukka/run-vcpkg/main/dist/index.js:4920:19)
    at VcpkgRunner.<anonymous> (/home/runner/work/_actions/lukka/run-vcpkg/main/dist/index.js:5702:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/lukka/run-vcpkg/main/dist/index.js:5511:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: run-vcpkg action execution failed: Error: Last command execution failed with error code '1'.
```

any assistance or tips would be appreciated.

**Comment by ericfont** [comment]
I earlier was trying the hosted-basic example, but also got an error...the error log suggests to submitting an issue to vcpkg (which I did https://github.com/microsoft/vcpkg/issues/20471) though I have a feeling the error is from me not understanding your system.

**Comment by lukka** [comment]
@ericfont thanks for reporting the problem. The problem is very likely belonging to vcpkg, and its root cause could be understood if you look to the content of log files provided by vcpkg, i.e.:

```
/home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/buildtrees/wxwidgets/config-x64-linux-dbg-out.log
/home/runner/work/Examples_wxWidgets/Examples_wxWidgets/vcpkg/buildtrees/wxwidgets/config-x64-linux-dbg-err.log
```

Note that everything after the text `Additionally, attach any relevant sections from the log files above.` belong to the `run-vcpkg` action output, and that part is not interesting to the vcpkg team.

**Comment by ericfont** [comment]
indeed that was a vcpkg build error and it was due to wxwidgets relying on gtk library which is at version 4 in the current vcpkg repo while unfortunately wxwidgets does not yet support gtk4.  The vcpkg maintainers suggested I try to figure out how to use versions in manifest file to build gtk3 and have wxwidgets build with that gtk3.  I will try that, and so will close this issue here because that isn't relevant to your repo here.

I will add that I succesfully was able to use your hosted-pure-workflow to make the bare-bones fibonacci example program build both online and locally with the same setup.  So thank you for that nice workflow...now I have a consistent way of building packages locally and online on all the 3 major OSes.  I'll share here incase anyone else might find it useful as a starting point for a repo:

https://github.com/ericfont/fibo-vcpkg-example/tree/v0.1
