### ISSUE TITLE
Triplet for v10

### ISSUE THREAD

**Issue by Sander0542** [lukka/CppBuildTasks-Validation#12]
How can I use a custom triplet in this action?

I am using this workflow file as base: https://github.com/lukka/CppBuildTasks-Validation/blob/v10/.github/workflows/hosted-ninja-vcpkg_submod.yml

**Comment by lukka** [comment]
@Sander0542  good question, it is something not documented yet. The answer is that for both [run-vcpkg](https://github.com/lukka/run-vcpkg/blob/main/action.yml) and [run-cmake](https://github.com/lukka/run-cmake/blob/main/action.yml), the usual vcpkg's environment variable could be used, that is `VCPKG_DEFAULT_TRIPLET`. The same variable is used by the actions itself when needed, check in their `actions.yml` files. 

Note, you need to define the env var using this syntax, or at [job level](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idenv) if it is needed on multiple steps:

```yaml
  - uses: lukka/run-vcpkg@v10
    env:
      VCPKG_DEFAULT_TRIPLET: custom-triplet
```

I need to document this on the project template I created in here that should be the starting point for using both `run-vcpkg` or `run-cmake`: https://github.com/lukka/CppCMakeVcpkgTemplate. You may want to open a ticket in there as well, thanks!
