### ISSUE TITLE
pin old librairies versions modifing baseline do not work

### ISSUE THREAD

**Issue by mbonani** [lukka/CppBuildTasks-Validation#14]
In https://vcpkg.readthedocs.io/en/latest/examples/modify-baseline-to-pin-old-boost/ a method explains how to use older libraries version modifing baselin file. It seems that it is not working with run-vcpkg because there is no vcpkg.json file.
Is there a way to do it ?

**Comment by lukka** [comment]
@mbonani the official docs of vcpkg have been moved here now: https://vcpkg.io/en/docs/examples/modify-baseline-to-pin-old-boost.html
It is certainly possible to use a `vcpkg.json` file (it is up to you to provide it), just take a look to the quickstart section of [`run-vcpkg`](https://github.com/lukka/run-vcpkg).

**Comment by mbonani** [comment]
Thank you for the doc,  I see the run-vcpkg for github, but I try to run in Azure-Devops and with the tool I cannot  pass  a .json

**Comment by mbonani** [comment]
I just see now I probably put my issue in the wrong repo.
