### ISSUE TITLE
not found specified version library

### ISSUE THREAD

**Issue by IronsDu** [lukka/CppBuildTasks-Validation#16]
Hello, I use run-vcpkg for test my gayrpc. But when generate cmake, It not found specified library.

Please see this workflow:
https://github.com/IronsDu/gayrpc/runs/7740655991?check_suite_focus=true

```
Error: No version entry for brynet at version 1.12.1. This may be fixed by updating vcpkg to the latest master via `git pull`.
  Available versions:
      1.11.2
      1.11.1#1
      1.11.0#1
      1.11.0
      1.10.0
      1.0.7
      1.0.5
      1.0.3
      1.0.2
      1.0.0-1
      1.0.0
      0.9.0
```

But, the latest  brynet version in vcpkg is 1.12.1 : https://github.com/microsoft/vcpkg/blob/master/ports/brynet/vcpkg.json .

Whether you need update your vcokg submodule  in `[CppBuildTasks-Validation](https://github.com/lukka/CppBuildTasks-Validation)` ?

**Comment by lukka** [comment]
@IronsDu this repository is only used for validating changes and features of the [run-vcpkg](https://github.com/lukka/run-vcpkg), [get-cmake](https://github.com/lukka/get-cmake) and [run-cmake](https://github.com/lukka/run-cmake) actions.

You may change your workflow file to use the desired version of vcpkg, which currently uses [version `678c...`](https://github.com/IronsDu/gayrpc/actions/runs/2823342091/workflow#L25)

**Comment by IronsDu** [comment]
@lukka Thank you. I put one wrong commit id.
